name: music-box

on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches: master

jobs:
  musicbox:
   runs-on: macos-latest

   steps:
     - uses: actions/checkout@v2
     - run: npm install
     - name: Update
       uses: ./
       env:
          LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LFMUSERNAME: ${{ secrets.LFMUSERNAME }}
          GIST_ID: ${{ secrets.GIST_ID }}

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
